# Generated by Django 4.2.2 on 2024-09-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created_at',), 'permissions': [('can_edit_is_published', 'Can edit is published'), ('can_edit_body', 'Can edit body'), ('can_edit_title', 'Can edit title'), ('can_edit_preview', 'Can edit preview')], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
