# Generated by Django 5.0.7 on 2024-09-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='номер версии'),
        ),
    ]
