# Generated by Django 4.2.2 on 2024-09-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title', 'category', 'price'), 'permissions': [('change_is_published', 'User can change the status of product'), ('change_description', 'User can change the description of product'), ('change_category', 'User can change the category of product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано?'),
        ),
    ]
